BEGIN;

CREATE TABLE hotspot_profiles (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name                 VARCHAR(120) NOT NULL,
    rx_rate              BIGINT NOT NULL DEFAULT 0,
    tx_rate              BIGINT NOT NULL DEFAULT 0,
    session_uptime_limit INTEGER NOT NULL DEFAULT 0,
    keepalive_timeout    INTEGER NOT NULL DEFAULT 90,
    created_by           BIGINT REFERENCES users (id),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id)
);

CREATE INDEX idx_profiles_tenant ON hotspot_profiles (tenant_id);

CREATE TABLE routers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name         VARCHAR(120) NOT NULL,
    ip_address   INET NOT NULL,
    api_port     INTEGER NOT NULL DEFAULT 8728,
    username     VARCHAR(120) NOT NULL,
    password_enc TEXT NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'unverified'
                 CHECK (status IN ('unverified', 'online', 'offline')),
    last_seen_at TIMESTAMPTZ,
    last_sync_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id)
);

CREATE INDEX idx_routers_tenant ON routers (tenant_id);
CREATE INDEX idx_routers_ip ON routers (ip_address);

CREATE TABLE hotspots (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    router_id      BIGINT NOT NULL,
    profile_id     BIGINT NOT NULL,
    name           VARCHAR(120) NOT NULL,
    mikrotik_id    VARCHAR(120),
    ip_range       CIDR,
    status         VARCHAR(20) NOT NULL DEFAULT 'configuring'
                   CHECK (status IN ('configuring', 'active', 'disabled', 'error')),
    last_config_at TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_hotspot_router
        FOREIGN KEY (tenant_id, router_id) REFERENCES routers (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_hotspot_profile
        FOREIGN KEY (tenant_id, profile_id) REFERENCES hotspot_profiles (tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_hotspots_tenant ON hotspots (tenant_id);
CREATE INDEX idx_hotspots_router ON hotspots (router_id);
CREATE INDEX idx_hotspots_status ON hotspots (status);

COMMIT;