BEGIN;

CREATE TABLE voucher_batches (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name       VARCHAR(120) NOT NULL,
    quantity   INTEGER NOT NULL CHECK (quantity > 0),
    price      NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    duration   INTEGER NOT NULL CHECK (duration > 0),
    profile_id BIGINT NOT NULL,
    valid_from TIMESTAMPTZ,
    valid_to   TIMESTAMPTZ,
    created_by BIGINT REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_batch_profile
        FOREIGN KEY (tenant_id, profile_id) REFERENCES hotspot_profiles (tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_batches_tenant ON voucher_batches (tenant_id);
CREATE INDEX idx_batches_created ON voucher_batches (created_at);

CREATE TABLE vouchers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    batch_id    BIGINT NOT NULL,
    code        VARCHAR(20) NOT NULL UNIQUE,
    status      VARCHAR(20) NOT NULL DEFAULT 'unused'
                CHECK (status IN ('unused', 'redeemed', 'expired', 'revoked')),
    redeemed_at TIMESTAMPTZ,
    redeemed_by BIGINT REFERENCES users (id),
    expires_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_voucher_batch
        FOREIGN KEY (tenant_id, batch_id) REFERENCES voucher_batches (tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX idx_vouchers_tenant ON vouchers (tenant_id);
CREATE INDEX idx_vouchers_batch ON vouchers (batch_id);
CREATE INDEX idx_vouchers_status ON vouchers (status);
CREATE INDEX idx_vouchers_expires ON vouchers (expires_at);

COMMIT;