BEGIN;

CREATE TABLE sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    hotspot_id  BIGINT NOT NULL,
    router_id   BIGINT NOT NULL,
    mac_address VARCHAR(17),
    ip_address  INET,
    username    VARCHAR(120) NOT NULL,
    voucher_id  BIGINT,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    state       VARCHAR(20) NOT NULL DEFAULT 'active'
                CHECK (state IN ('active', 'closing', 'closed')),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_session_hotspot
        FOREIGN KEY (tenant_id, hotspot_id) REFERENCES hotspots (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_session_router
        FOREIGN KEY (tenant_id, router_id) REFERENCES routers (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_session_voucher
        FOREIGN KEY (tenant_id, voucher_id) REFERENCES vouchers (tenant_id, id) ON DELETE SET NULL
);

CREATE INDEX idx_sessions_tenant ON sessions (tenant_id);
CREATE INDEX idx_sessions_hotspot ON sessions (hotspot_id);
CREATE INDEX idx_sessions_state ON sessions (state);
CREATE INDEX idx_sessions_last_seen ON sessions (last_seen_at);

CREATE TABLE usage_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    session_id    BIGINT NOT NULL REFERENCES sessions (id) ON DELETE RESTRICT,
    voucher_id    BIGINT,
    started_at    TIMESTAMPTZ NOT NULL,
    ended_at      TIMESTAMPTZ NOT NULL,
    duration_sec  INTEGER NOT NULL DEFAULT 0 CHECK (duration_sec >= 0),
    bytes_rx      BIGINT NOT NULL DEFAULT 0 CHECK (bytes_rx >= 0),
    bytes_tx      BIGINT NOT NULL DEFAULT 0 CHECK (bytes_tx >= 0),
    amount        NUMERIC(12, 2),
    billing_status VARCHAR(20) NOT NULL DEFAULT 'unpaid'
                   CHECK (billing_status IN ('unpaid', 'paid')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_usage_voucher
        FOREIGN KEY (tenant_id, voucher_id) REFERENCES vouchers (tenant_id, id) ON DELETE SET NULL
);

CREATE INDEX idx_usage_tenant ON usage_logs (tenant_id);
CREATE INDEX idx_usage_started ON usage_logs (started_at);

COMMIT;