BEGIN;

CREATE TABLE settings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL UNIQUE REFERENCES tenants (id) ON DELETE CASCADE,
    portal_title    VARCHAR(120) NOT NULL DEFAULT 'Free Wi-Fi',
    portal_message  TEXT,
    payment_config  JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT REFERENCES tenants (id) ON DELETE CASCADE,
    user_id     BIGINT REFERENCES users (id) ON DELETE SET NULL,
    action      VARCHAR(120) NOT NULL,
    entity_type VARCHAR(80),
    entity_id   BIGINT,
    meta        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_tenant_created ON audit_logs (tenant_id, created_at);

COMMIT;