BEGIN;

CREATE TABLE daily_metrics (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    day            DATE NOT NULL,
    sessions       INTEGER NOT NULL DEFAULT 0,
    vouchers_sold  INTEGER NOT NULL DEFAULT 0,
    bytes_rx       BIGINT NOT NULL DEFAULT 0,
    bytes_tx       BIGINT NOT NULL DEFAULT 0,
    amount         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    UNIQUE (tenant_id, day)
);

CREATE INDEX idx_metrics_tenant_day ON daily_metrics (tenant_id, day);

COMMIT;