BEGIN;

-- Phase 6: payments, rate boost windows, anomaly detection, config jobs

CREATE TABLE payments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    voucher_id     BIGINT,
    external_ref   VARCHAR(120) NOT NULL UNIQUE,
    amount         NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    fee            NUMERIC(12, 2) NOT NULL DEFAULT 0,
    net_amount     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status         VARCHAR(20) NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded')),
    payment_method VARCHAR(40) NOT NULL DEFAULT 'mock',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_payment_voucher
        FOREIGN KEY (tenant_id, voucher_id) REFERENCES vouchers (tenant_id, id) ON DELETE SET NULL
);

CREATE INDEX idx_payments_tenant ON payments (tenant_id);

CREATE TABLE rate_windows (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    hotspot_id       BIGINT NOT NULL,
    boost_multiplier NUMERIC(5, 2) NOT NULL CHECK (boost_multiplier > 1),
    effective_from   TIMESTAMPTZ NOT NULL,
    effective_until  TIMESTAMPTZ NOT NULL,
    repeat           JSONB NOT NULL DEFAULT '{}'::jsonb,
    note             VARCHAR(255),
    created_by       BIGINT REFERENCES users (id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_ratewindow_hotspot
        FOREIGN KEY (tenant_id, hotspot_id) REFERENCES hotspots (tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX idx_ratewindows_tenant ON rate_windows (tenant_id);

CREATE TABLE anomaly_alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    hotspot_id      BIGINT,
    router_id       BIGINT,
    session_id      BIGINT,
    type            VARCHAR(40) NOT NULL,
    severity        VARCHAR(20) NOT NULL DEFAULT 'warning'
                    CHECK (severity IN ('info', 'warning', 'critical')),
    status          VARCHAR(20) NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'acknowledged', 'resolved', 'dismissed')),
    value           NUMERIC(16, 2) NOT NULL DEFAULT 0,
    baseline        NUMERIC(16, 2) NOT NULL DEFAULT 0,
    fingerprint     VARCHAR(64) NOT NULL,
    occurrences     INTEGER NOT NULL DEFAULT 1,
    rate_window_id  BIGINT,
    acked_at        TIMESTAMPTZ,
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id)
);

CREATE INDEX idx_anomaly_tenant_status ON anomaly_alerts (tenant_id, status, severity, created_at);

CREATE TABLE anomaly_summaries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    hotspot_id      BIGINT NOT NULL,
    type            VARCHAR(40) NOT NULL,
    severity        VARCHAR(20) NOT NULL,
    bucket_start    TIMESTAMPTZ NOT NULL,
    open_count      INTEGER NOT NULL DEFAULT 0,
    total_count     INTEGER NOT NULL DEFAULT 0,
    resolved_count  INTEGER NOT NULL DEFAULT 0,
    value_sum       NUMERIC(16, 2) NOT NULL DEFAULT 0,
    first_seen      TIMESTAMPTZ,
    last_seen       TIMESTAMPTZ,
    UNIQUE (tenant_id, hotspot_id, type, severity, bucket_start)
);

CREATE INDEX idx_anomaly_summary_tenant ON anomaly_summaries (tenant_id, bucket_start);

CREATE TABLE config_jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    hotspot_id  BIGINT NOT NULL REFERENCES hotspots (id) ON DELETE CASCADE,
    action      VARCHAR(20) NOT NULL DEFAULT 'apply'
                CHECK (action IN ('apply', 'revert')),
    payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
    status      VARCHAR(20) NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'done', 'failed')),
    attempts    INTEGER NOT NULL DEFAULT 0,
    last_error  TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_configjobs_tenant_status ON config_jobs (tenant_id, status);

-- extend hotspots/sessions/usage for rate-window tracking and session accounting
ALTER TABLE hotspots ADD COLUMN applied_multiplier NUMERIC(5, 2) NOT NULL DEFAULT 1;
ALTER TABLE sessions ADD COLUMN rate_window_id BIGINT;
ALTER TABLE sessions ADD COLUMN profile_id BIGINT;
ALTER TABLE sessions ADD COLUMN password VARCHAR(120);
ALTER TABLE sessions ADD COLUMN end_time TIMESTAMPTZ;
ALTER TABLE sessions ADD COLUMN bytes_rx BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN bytes_tx BIGINT NOT NULL DEFAULT 0;
ALTER TABLE usage_logs ADD COLUMN rate_window_id BIGINT;

ALTER TABLE sessions
    ADD CONSTRAINT fk_session_profile
        FOREIGN KEY (tenant_id, profile_id) REFERENCES hotspot_profiles (tenant_id, id) ON DELETE RESTRICT;

CREATE UNIQUE INDEX uq_usage_session_started ON usage_logs (session_id, started_at);

CREATE INDEX idx_sessions_username ON sessions (tenant_id, hotspot_id, username);

COMMIT;