BEGIN;

CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    hotspot_id  BIGINT,
    name        VARCHAR(120) NOT NULL,
    phone       VARCHAR(30)  NOT NULL DEFAULT '',
    address     TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'token', 'expired', 'suspended')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_customer_hotspot
        FOREIGN KEY (tenant_id, hotspot_id) REFERENCES hotspots (tenant_id, id) ON DELETE SET NULL
);

CREATE INDEX idx_customers_tenant ON customers (tenant_id);
CREATE INDEX idx_customers_tenant_status ON customers (tenant_id, status);

CREATE TABLE billing_windows (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    customer_id   BIGINT NOT NULL,
    period_start  DATE NOT NULL,
    period_end    DATE NOT NULL,
    amount        NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    status        VARCHAR(20) NOT NULL DEFAULT 'issued'
                  CHECK (status IN ('draft', 'issued', 'paid', 'overdue')),
    issued_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at       TIMESTAMPTZ,
    UNIQUE (tenant_id, id),
    UNIQUE (customer_id, period_start),
    CONSTRAINT fk_billing_customer
        FOREIGN KEY (tenant_id, customer_id) REFERENCES customers (tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX idx_billing_tenant ON billing_windows (tenant_id, status, period_start);
CREATE INDEX idx_billing_customer ON billing_windows (customer_id);

COMMIT;