BEGIN;

ALTER TABLE customers ADD COLUMN balance NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (balance >= 0);

CREATE TABLE wallet_transactions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    customer_id   BIGINT NOT NULL,
    type          VARCHAR(20) NOT NULL DEFAULT 'topup'
                  CHECK (type IN ('topup', 'bill_payment', 'adjustment')),
    amount        NUMERIC(12, 2) NOT NULL,
    balance_after NUMERIC(12, 2) NOT NULL,
    ref_type      VARCHAR(20),
    ref_id        BIGINT,
    note          VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, id),
    CONSTRAINT fk_wallet_customer
        FOREIGN KEY (tenant_id, customer_id) REFERENCES customers (tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX idx_wallet_tx_customer ON wallet_transactions (tenant_id, customer_id, id DESC);

-- Time payments polymorphic: keep voucher payments, add wallet top-ups.
ALTER TABLE payments ADD COLUMN customer_id BIGINT;
ALTER TABLE payments ADD COLUMN entity_type VARCHAR(20) NOT NULL DEFAULT 'voucher'
    CHECK (entity_type IN ('voucher', 'wallet_topup'));

ALTER TABLE payments
    ADD CONSTRAINT fk_payment_customer
    FOREIGN KEY (tenant_id, customer_id) REFERENCES customers (tenant_id, id) ON DELETE SET NULL;

-- At most one pending/live top-up payment per customer (idempotency guard).
CREATE UNIQUE INDEX uq_payment_topup ON payments (tenant_id, customer_id)
    WHERE entity_type = 'wallet_topup' AND status IN ('pending', 'succeeded');

COMMIT;